server:
  port: 80

spring:
  application:
    name: consumerProduct

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中  \
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true # 访问路径可以显示IP地址
    #用来修改eureka server默认接受心跳的最大时间 默认是90s
    lease-expiration-duration-in-seconds: 10
    #指定客户端多久向eureka server发送一次心跳 默认是30s
    lease-renewal-interval-in-seconds: 5